xcopy /s/e/y ".\app\views" ".\Android\www\views"
xcopy /s/e/y ".\app\scripts" ".\Android\www\scripts"
xcopy /s/e/y ".\app\resources" ".\Android\www\resources"
xcopy /s/e/y ".\app\styles" ".\Android\www\styles"
xcopy /s/e/y ".\app\index.html" ".\Android\www"

xcopy /s/e/y ".\app\views" ".\Firefox\www\views"
xcopy /s/e/y ".\app\scripts" ".\Firefox\www\scripts"
xcopy /s/e/y ".\app\resources" ".\Firefox\www\resources"
xcopy /s/e/y ".\app\styles" ".\Firefox\www\styles"
xcopy /s/e/y ".\app\index.html" ".\Firefox\www"